### ISSUE TITLE
WDCPLOT reset causes focus to go to top of page rather than stay within the plot area

### ISSUE THREAD

**Issue by robert-a** [att/rcloud.dcplot#12]
After selecting on a plot within wdcplot, then using the 'reset' to return to the full selection, the focus moves to the top of the page rather than within the wdcplot area. This is an issue when wdcplot is embedded in a larger page (e.g., in mini.html). Note, when re-clicking on the previous selection instead, it returns to the full selection without moving the focus, as would be expected/desired.

**Comment by gordonwoodhull** [comment]
Thanks for the report, @robert-a. 

Do you mean the keyboard focus? Does the window scroll in response?

**Comment by robert-a** [comment]
Yes, the cursor and the window scroll back to the top.

**Comment by gordonwoodhull** [comment]
Hmm, I suspect this is more a problem with a link getting focus and then being deleted, than anything else. Still, I'll see if there's anything I can do about it.

**Comment by robert-a** [comment]
I think there is an href=”#”

**Comment by gordonwoodhull** [comment]
Oh, the event needs a `.preventDefault()` or something. Gotcha. Thanks!

**Comment by gordonwoodhull** [comment]
Fixed in 0.3
